In [60]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.pipeline import  Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler,OneHotEncoder

from sklearn.compose import ColumnTransformer

from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier,GradientBoostingClassifier

from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score,classification_report,confusion_matrix

import joblib

In [61]:
df = pd.read_csv('../data/raw/Brest_cancer_data.csv')
df.head()

   Sample code number  Clump Thickness  ...  Mitoses  Class
0             1000025                5  ...        1      2
1             1002945                5  ...        1      2
2             1015425                3  ...        1      2
3             1016277                6  ...        1      2
4             1017023                4  ...        1      2

[5 rows x 11 columns]

In [62]:
df.shape

(683, 11)

In [63]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 683 entries, 0 to 682
Data columns (total 11 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Sample code number           683 non-null    int64
 1   Clump Thickness              683 non-null    int64
 2   Uniformity of Cell Size      683 non-null    int64
 3   Uniformity of Cell Shape     683 non-null    int64
 4   Marginal Adhesion            683 non-null    int64
 5   Single Epithelial Cell Size  683 non-null    int64
 6   Bare Nuclei                  683 non-null    int64
 7   Bland Chromatin              683 non-null    int64
 8   Normal Nucleoli              683 non-null    int64
 9   Mitoses                      683 non-null    int64
 10  Class                        683 non-null    int64
dtypes: int64(11)
memory usage: 58.8 KB

In [64]:
df.describe().T

                             count          mean  ...        75%         max
Sample code number           683.0  1.076720e+06  ...  1238705.0  13454352.0
Clump Thickness              683.0  4.442167e+00  ...        6.0        10.0
Uniformity of Cell Size      683.0  3.150805e+00  ...        5.0        10.0
Uniformity of Cell Shape     683.0  3.215227e+00  ...        5.0        10.0
Marginal Adhesion            683.0  2.830161e+00  ...        4.0        10.0
Single Epithelial Cell Size  683.0  3.234261e+00  ...        4.0        10.0
Bare Nuclei                  683.0  3.544656e+00  ...        6.0        10.0
Bland Chromatin              683.0  3.445095e+00  ...        5.0        10.0
Normal Nucleoli              683.0  2.869693e+00  ...        4.0        10.0
Mitoses                      683.0  1.603221e+00  ...        1.0        10.0
Class                        683.0  2.699854e+00  ...        4.0         4.0

[11 rows x 8 columns]

In [65]:
print(df.nunique())

Sample code number             630
Clump Thickness                 10
Uniformity of Cell Size         10
Uniformity of Cell Shape        10
Marginal Adhesion               10
Single Epithelial Cell Size     10
Bare Nuclei                     10
Bland Chromatin                 10
Normal Nucleoli                 10
Mitoses                          9
Class                            2
dtype: int64

In [66]:
df.duplicated().sum()
df  = df.drop_duplicates().reset_index(drop=True)

In [85]:
X = df.drop(columns=['Sample code number','Class'])
y = df['Class'].map({
    2:0,
    4:1
})

In [86]:
X_train,X_test,y_train,y_test = train_test_split(
    X,
    y,
    test_size=.2,
    stratify=y,
    random_state=42
)

In [87]:
numerical_features = X.select_dtypes(include=np.number).columns.tolist()
categorical_features = X.select_dtypes(include='object').columns.tolist()

In [88]:
numerical_pipeline = Pipeline([
    ('imputer',SimpleImputer(strategy='median')),
    ('scaler',StandardScaler())
])


categorical_pipeline = Pipeline([
    ('imputer',SimpleImputer (strategy='most_frequent')),
    ('encoder',OneHotEncoder(handle_unknown='ignore'))
])

In [89]:
preprocessor = ColumnTransformer([
    ('numerical',numerical_pipeline,numerical_features)
])

In [90]:
logistic = LogisticRegression(
    max_iter=1000,
    random_state=42
)

svm = SVC(
    kernel='rbf',
    probability=True,
    random_state=42
)


radom_forest = RandomForestClassifier(
    n_estimators=200,
    random_state=42
)

gradient = GradientBoostingClassifier(
    random_state=42
)

In [91]:
logistic_model = Pipeline([
    ('preprocessor',preprocessor),
    ('logistic',logistic)
])

svm_model = Pipeline([
    ('preprocessor',preprocessor),
    ('svm',svm)
])

forest_model = Pipeline([
    ('preprocessor',preprocessor),
    ('Random Forest',radom_forest)
])

gradient_model = Pipeline([
    ('preprocessor',preprocessor),
    ('gradient',gradient)
])

In [92]:
logistic_model.fit(X_train,y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('numerical',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['Clump Thickness',
                                                   'Uniformity of Cell Size',
                                                   'Uniformity of Cell Shape',
                                                   'Marginal Adhesion',
                                                   'Single Epithelial Cell '
                                                   'Size',
                                                   'Bare Nuclei',
                                                   'Bland Chromatin',
                                                   'Normal Nucleoli',
                                                   'Mitoses'])])),
                ('logistic',
                 LogisticRegression(max_iter=1000, random_state=42))])

In [93]:
svm_model.fit(X_train,y_train)

/home/loq/miniconda3/envs/tensorflow/lib/python3.12/site-packages/sklearn/svm/_base.py:239: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('numerical',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['Clump Thickness',
                                                   'Uniformity of Cell Size',
                                                   'Uniformity of Cell Shape',
                                                   'Marginal Adhesion',
                                                   'Single Epithelial Cell '
                                                   'Size',
                                                   'Bare Nuclei',
                                                   'Bland Chromatin',
                                                   'Normal Nucleoli',
                                                   'Mitoses'])])),
                ('svm', SVC(probability=True, random_state=42))])

In [94]:
forest_model.fit(X_train,y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('numerical',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['Clump Thickness',
                                                   'Uniformity of Cell Size',
                                                   'Uniformity of Cell Shape',
                                                   'Marginal Adhesion',
                                                   'Single Epithelial Cell '
                                                   'Size',
                                                   'Bare Nuclei',
                                                   'Bland Chromatin',
                                                   'Normal Nucleoli',
                                                   'Mitoses'])])),
                ('Random Forest',
                 RandomForestClassifier(n_estimators=200, random_state=42))])

In [95]:
gradient_model.fit(X_train,y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('numerical',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['Clump Thickness',
                                                   'Uniformity of Cell Size',
                                                   'Uniformity of Cell Shape',
                                                   'Marginal Adhesion',
                                                   'Single Epithelial Cell '
                                                   'Size',
                                                   'Bare Nuclei',
                                                   'Bland Chromatin',
                                                   'Normal Nucleoli',
                                                   'Mitoses'])])),
                ('gradient', GradientBoostingClassifier(random_state=42))])

In [96]:
models = {
    "Logistic Regression": logistic_model,
    "SVM": svm_model,
    "Random Forest": forest_model,
    "Gradient Boosting": gradient_model
}

In [97]:
results = []

for name, model in models.items():

    model.fit(X_train, y_train)

    y_pred = model.predict(X_test)

    results.append({
        "Model": name,
        "Accuracy": accuracy_score(y_test, y_pred),
        "Precision": precision_score(y_test, y_pred),
        "Recall": recall_score(y_test, y_pred),
        "F1": f1_score(y_test, y_pred)
    })

results_df = pd.DataFrame(results)

results_df

/home/loq/miniconda3/envs/tensorflow/lib/python3.12/site-packages/sklearn/svm/_base.py:239: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(

                 Model  Accuracy  Precision    Recall        F1
0  Logistic Regression  0.955556    0.93617  0.936170  0.936170
1                  SVM  0.962963    0.93750  0.957447  0.947368
2        Random Forest  0.962963    0.93750  0.957447  0.947368
3    Gradient Boosting  0.955556    0.93617  0.936170  0.936170

In [98]:
results_df = results_df.sort_values(
    by="F1",
    ascending=False
).reset_index(drop=True)

results_df

                 Model  Accuracy  Precision    Recall        F1
0                  SVM  0.962963    0.93750  0.957447  0.947368
1        Random Forest  0.962963    0.93750  0.957447  0.947368
2  Logistic Regression  0.955556    0.93617  0.936170  0.936170
3    Gradient Boosting  0.955556    0.93617  0.936170  0.936170

In [99]:
results_df.iloc[0]

Model             SVM
Accuracy     0.962963
Precision      0.9375
Recall       0.957447
F1           0.947368
Name: 0, dtype: object

In [100]:
best_model_name = results_df.loc[0, "Model"]

print("Best Model:", best_model_name)

Best Model: SVM

In [101]:
best_model = models[best_model_name]

print(best_model)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('numerical',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['Clump Thickness',
                                                   'Uniformity of Cell Size',
                                                   'Uniformity of Cell Shape',
                                                   'Marginal Adhesion',
                                                   'Single Epithelial Cell '
                                                   'Size',
                                                   'Bare Nuclei',
                                                   'Bland Chromatin',
                                                   'Normal Nucleoli',
                                                   'Mitoses'])])),
                ('svm', SVC(probability=True, random_state=42))])

In [102]:
best_model.fit(X, y)

/home/loq/miniconda3/envs/tensorflow/lib/python3.12/site-packages/sklearn/svm/_base.py:239: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('numerical',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['Clump Thickness',
                                                   'Uniformity of Cell Size',
                                                   'Uniformity of Cell Shape',
                                                   'Marginal Adhesion',
                                                   'Single Epithelial Cell '
                                                   'Size',
                                                   'Bare Nuclei',
                                                   'Bland Chromatin',
                                                   'Normal Nucleoli',
                                                   'Mitoses'])])),
                ('svm', SVC(probability=True, random_state=42))])

In [103]:
from pathlib import Path
import joblib

model_path = Path("../models/breast_cancer_model.pkl")

model_path.parent.mkdir(
    parents=True,
    exist_ok=True
)

joblib.dump(
    best_model,
    model_path
)

print(f"Model saved successfully: {model_path}")

Model saved successfully: ../models/breast_cancer_model.pkl